using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
 * Contains sample not data for testing purposes. 
 * A level editor that automatically generates level files instead of this container class is under development...
 */
public class MusicData
{
    public List<Note> getMusicData(int index = 0)
    {
        Debug.Log("index = " + index);
        if (index == -1)
        {
            return testData;
        }
        return data[index];
    }

    private List<Note> testData = new List<Note>()
    {
        new Note(0.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(1.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(2.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(3.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(4.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(5.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(6.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(7.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(8.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(9.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(10.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(11.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(12.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(13.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(14.0, InputHandler.Input.ANY, Note.Position.RIGHT),
        new Note(15.0, InputHandler.Input.ANY, Note.Position.RIGHT),
    };

    private List<List<Note>> data = new List<List<Note>>()
    {
        new List<Note>()
        {
            new Note(-1.5),
            new Note(-1.0),
            new Note(-0.5),
            new Note(0.0),

            new Note(2.5),
            new Note(3.0),
            new Note(3.5),
            new Note(4.0),

            new Note(6.5),
            new Note(7.0),
            new Note(7.5),
            new Note(8.0),

            new Note(9.5),
            new Note(9.75),
            new Note(10.0),
            new Note(10.25),
            new Note(10.5),
            new Note(11.0),
            new Note(11.5),
            new Note(12.0),

            new Note(14.5),
            new Note(15.25),
            new Note(16.0),

            new Note(17.5),
            new Note(17.75),
            new Note(18.0),
            new Note(18.25),
            new Note(18.5),
            new Note(19.0),
            new Note(19.5),
            new Note(20.0),

            new Note(21.5),
            new Note(22.0),

            new Note(24.0),
            new Note(24.75),
            new Note(25.5),
            new Note(26.25),
            new Note(27.0),
            new Note(27.5),
            new Note(28.0),

            // ====

            new Note(31-0.5),
            new Note(31+0),
            new Note(31+0.5),
            new Note(31+1),

            new Note(31+3.5),
            new Note(31+4),
            new Note(31+4.5),
            new Note(31+5),

            new Note(31+7.5),
            new Note(31+8),
            new Note(31+8.5),
            new Note(31+9),

            new Note(31+10.5),
            new Note(31+10.75),
            new Note(31+11),
            new Note(31+11.25),
            new Note(31+11.5),
            new Note(31+12),
            new Note(31+12.5),
            new Note(31+13),

            new Note(31+15.5),
            new Note(31+16.25),
            new Note(31+17),

            new Note(31+18.5),
            new Note(31+18.75),
            new Note(31+19),
            new Note(31+19.25),
            new Note(31+19.5),
            new Note(31+20),
            new Note(31+20.5),
            new Note(31+21),

            new Note(31+22.5),
            new Note(31+23),

            new Note(31+25),
            new Note(31+25.75),
            new Note(31+26.5),
            new Note(31+27.25),
            new Note(31+28),
            new Note(31+28.5),
            new Note(31+29),

            // ====

            new Note(63-0.5),
            new Note(63+0),
            new Note(63+0.5),
            new Note(63+1),

            new Note(63+2.5),
            new Note(63+2.75),
            new Note(63+3),
            new Note(63+3.25),
            new Note(63+3.5),
            new Note(63+4),
            new Note(63+4.5),
            new Note(63+5),

            new Note(63+7.5),
            new Note(63+8),
            new Note(63+8.5),
            new Note(63+9),

            new Note(63+10.5),
            new Note(63+10.75),
            new Note(63+11),
            new Note(63+11.25),
            new Note(63+11.5),
            new Note(63+12),
            new Note(63+12.5),
            new Note(63+13),

            new Note(63+15.5),
            new Note(63+16),
            new Note(63+16.5),
            new Note(63+17),

            new Note(63+18.5),
            new Note(63+18.75),
            new Note(63+19),
            new Note(63+19.25),
            new Note(63+19.5),
            new Note(63+20),
            new Note(63+20.5),
            new Note(63+21),

            new Note(63+22.5),
            new Note(63+23),

            new Note(63+24.25),
            new Note(63+24.5),
            new Note(63+24.75),
            new Note(63+25),
            new Note(63+25.75),
            new Note(63+26.5),
            new Note(63+27.25),
            new Note(63+28),
            new Note(63+28.5),
            new Note(63+29),

            // ====

            new Note(95-0.5),
            new Note(95+0),
            new Note(95+0.5),
            new Note(95+1),

            new Note(95+3.5),
            new Note(95+4),
            new Note(95+4.5),
            new Note(95+5),

            new Note(95+7.5),
            new Note(95+8),
            new Note(95+8.5),
            new Note(95+9),

            new Note(95+11.25),
            new Note(95+11.5),
            new Note(95+12),
            new Note(95+12.5),
            new Note(95+13),

            new Note(95+15.5),
            new Note(95+16.25),
            new Note(95+17),

            new Note(95+18.75),
            new Note(95+19),
            new Note(95+19.5),
            new Note(95+20),
            new Note(95+20.5),
            new Note(95+21),

            new Note(95+22.5),
            new Note(95+23),

            new Note(95+25),
            new Note(95+25.75),
            new Note(95+26.5),
            new Note(95+27.25),
            new Note(95+28),
            new Note(95+28.5),
            new Note(95+29),

            // ====

            new Note(95+31),
            new Note(95+31.25),
            new Note(95+31.5),
            new Note(95+31.75),
            new Note(95+32),
            new Note(95+32.25),
            new Note(95+32.5),
            new Note(95+32.75),

            new Note(127+1),
            new Note(127+1.25),
            new Note(127+1.5),
            new Note(127+1.75),

            new Note(127+5),

            new Note(127+9),
            new Note(127+9.25),
            new Note(127+9.5),
            new Note(127+9.75),

            new Note(127+13),
            new Note(127+13.25),
            new Note(127+13.5),
            new Note(127+13.75),

            new Note(144),
            new Note(145.75),
            new Note(146),
            new Note(146.5),
            new Note(147),
            new Note(147.5),
            new Note(148),

            new Note(149.5),

            new Note(152),
            new Note(156),

            // ----

            new Note(158.5),
            new Note(159),
            new Note(159.5),
            new Note(160),

            new Note(162.5),
            new Note(163),
            new Note(163.5),
            new Note(164),

            new Note(166.5),
            new Note(167),
            new Note(167.5),
            new Note(168),

            new Note(170.25),
            new Note(170.5),
            new Note(171),
            new Note(171.5),
            new Note(172),

            new Note(174.5),
            new Note(175.25),
            new Note(176),

            new Note(177.75),
            new Note(178),
            new Note(178.5),
            new Note(179),
            new Note(179.5),
            new Note(180),

            new Note(181.5),
            new Note(182),

            new Note(184),

            // ----

            new Note(190.5),
            new Note(191),
            new Note(191.5),
            new Note(192),

            new Note(194.5),
            new Note(195),
            new Note(195.5),
            new Note(196),

            new Note(198.5),
            new Note(199),
            new Note(199.5),
            new Note(200),

            new Note(201.5),
            new Note(201.75),
            new Note(202),
            new Note(202.25),
            new Note(202.5),
            new Note(203),
            new Note(203.5),
            new Note(204),

            new Note(206.5),
            new Note(207.25),
            new Note(208),

            new Note(209.5),
            new Note(209.75),
            new Note(210),
            new Note(210.25),
            new Note(210.5),
            new Note(211),
            new Note(211.5),
            new Note(212),

            new Note(213.5),
            new Note(214),

            new Note(216),
            new Note(216.75),
            new Note(217.5),
            new Note(218.25),
            new Note(219),
            new Note(219.5),
            new Note(220),
        },

        new List<Note>()
        {
            // INTRO part

            new Note(1.0-1),
            new Note(2.0-1),
            new Note(2.5-1),
            new Note(3.0-1),
            new Note(3.5-1),
            new Note(4.0-1),
            new Note(4.5-1),

            new Note(5.5-1),
            new Note(6.0-1),
            new Note(6.5-1),
            new Note(7.0-1),
            new Note(7.5-1),
            new Note(8.0-1),
            new Note(8.5-1),

            new Note(17.0-1),
            new Note(18.0-1),
            new Note(18.5-1),
            new Note(19.0-1),
            new Note(19.5-1),
            new Note(20.0-1),
            new Note(20.5-1),

            new Note(21.5-1),
            new Note(22.25-1),
            new Note(22.5-1),
            new Note(23.0-1),
            new Note(23.5-1),
            new Note(24.0-1),
            new Note(24.5-1),

            // FIRST PROLOGUE part

            new Note(42.0-1),
            new Note(42.5-1),
            new Note(43.0-1),
            new Note(43.5-1),
            new Note(44.0-1),
            new Note(44.5-1),
            new Note(45.5-1),
            new Note(46.0-1),
            new Note(46.5-1),
            new Note(47.0-1),
            new Note(47.5-1),
            new Note(48.0-1),
            new Note(48.5-1),

            new Note(58.0-1),
            new Note(58.5-1),
            new Note(59.0-1),
            new Note(59.5-1),
            new Note(60.0-1),
            new Note(60.5-1),
            new Note(61.5-1),
            new Note(62.25-1),
            new Note(62.5-1),
            new Note(63.0-1),
            new Note(63.5-1),
            new Note(64.0-1),
            new Note(64.5-1),

            // FIRST DROP part

            new Note(73.0-1),
            new Note(74.0-1),
            new Note(74.5-1),
            new Note(75.0-1),
            new Note(75.5-1),
            new Note(76.0-1),
            new Note(76.5-1),
            new Note(77.5-1),
            new Note(78.0-1),
            new Note(78.5-1),
            new Note(79.0-1),
            new Note(79.5-1),
            new Note(80.0-1),
            new Note(80.5-1),

            new Note(87.0-1),
            new Note(88.0-1),
            new Note(89.0-1),
            new Note(90.0-1),
            new Note(90.5-1),
            new Note(91.0-1),
            new Note(91.5-1),
            new Note(92.0-1),
            new Note(92.5-1),
            new Note(93.5-1),
            new Note(94.25-1),
            new Note(94.5-1),
            new Note(95.0-1),
            new Note(95.5-1),
            new Note(96.0-1),
            new Note(96.5-1),

            new Note(103.5-1),
            new Note(104.0-1),
            new Note(104.5-1),
            new Note(105.0-1),
            new Note(106.0-1),
            new Note(106.5-1),
            new Note(107.0-1),
            new Note(107.5-1),
            new Note(108.0-1),
            new Note(108.5-1),
            new Note(109.5-1),
            new Note(110.0-1),
            new Note(110.5-1),
            new Note(111.0-1),
            new Note(111.5-1),
            new Note(112.0-1),
            new Note(112.5-1),

            new Note(121.0-1),
            new Note(122.0-1),
            new Note(122.5-1),
            new Note(123.0-1),
            new Note(123.5-1),
            new Note(124.0-1),
            new Note(124.5-1),
            new Note(125.5-1),
            new Note(126.25-1),
            new Note(126.5-1),
            new Note(127.0-1),
            new Note(127.5-1),
            new Note(128.0-1),
            new Note(128.5-1),

            // MID part

            new Note(137.0-1),
            new Note(137.75-1),
            new Note(138.5-1),
            new Note(139.0-1),
            new Note(139.5-1),

            new Note(141.0-1),
            new Note(141.75-1),
            new Note(142.25-1),
            new Note(142.5-1),
            new Note(143.0-1),
            new Note(143.5-1),

            new Note(151.0-1),
            new Note(151.25-1),
            new Note(151.5-1),
            new Note(151.75-1),
            new Note(152.0-1),
            new Note(152.25-1),
            new Note(152.5-1),
            new Note(152.75-1),

            new Note(153.0-1),
            new Note(153.75-1),
            new Note(154.5-1),
            new Note(155.0-1),
            new Note(155.5-1),

            new Note(157.25-1),
            new Note(157.5-1),
            new Note(157.75-1),
            new Note(158.25-1),
            new Note(158.5-1),
            new Note(158.75-1),
            new Note(159.0-1),
            new Note(159.5-1),
            new Note(160.0-1),
            new Note(160.5-1),

            new Note(169.0-1),
            new Note(169.75-1),
            new Note(170.5-1),
            new Note(170.75-1),
            new Note(171.0-1),
            new Note(171.5-1),

            new Note(172.5-1),
            new Note(173.0-1),
            new Note(173.75-1),
            new Note(174.25-1),
            new Note(174.5-1),
            new Note(174.75-1),
            new Note(175.0-1),
            new Note(175.5-1),
            new Note(176.0-1),
            new Note(176.5-1),
            new Note(177.0-1),
            new Note(177.5-1),
            new Note(178.0-1),
            new Note(178.5-1),
            new Note(179.0-1),
            new Note(179.5-1),
            new Note(180.0-1),
            new Note(180.5-1),
            new Note(181.0-1),
            new Note(181.25-1),
            new Note(181.5-1),
            new Note(181.75-1),
            new Note(182.25-1),
            new Note(182.5-1),
            new Note(182.75-1),
            new Note(183.25-1),
            new Note(183.5-1),
            new Note(183.75-1),
            new Note(184.25-1),
            new Note(184.5-1),

            new Note(185.0-1),
            new Note(186.0-1),
            new Note(186.5-1),
            new Note(187.0-1),
            new Note(187.5-1),

            new Note(189.25-1),
            new Note(189.5-1),
            new Note(189.75-1),
            new Note(190.0-1),
            new Note(190.5-1),
            new Note(191.0-1),
            new Note(191.5-1),

            new Note(194.0-1),
            new Note(194.5-1),
            new Note(195.0-1),
            new Note(195.5-1),

            new Note(197.25-1),
            new Note(197.5-1),
            new Note(197.75-1),
            new Note(198.0-1),
            new Note(198.5-1),
            new Note(199.0-1),
            new Note(199.5-1),
            new Note(200.0-1),
            new Note(200.5-1),

            new Note(201.0-1),
            new Note(201.5-1),
            new Note(202.5-1),
            new Note(203.5-1),
            new Note(204.5-1),
            new Note(204.75-1),
            new Note(205.5-1),
            new Note(206.5-1),
            new Note(207.5-1),
            new Note(208.5-1),
            new Note(209.5-1),
            new Note(210.5-1),
            new Note(211.5-1),
            new Note(212.0-1),
            new Note(212.5-1),
            new Note(213.5-1),
            new Note(214.5-1),
            new Note(215.5-1),
            new Note(216.5-1),
            new Note(217.0-1),
            new Note(217.5-1),
            new Note(218.0-1),
            new Note(218.5-1),
            new Note(219.0-1),
            new Note(219.5-1),
            new Note(220.0-1),
            new Note(220.5-1),

            new Note(221.0-1),
            new Note(222.0-1),
            new Note(222.5-1),
            new Note(223.5-1),
            new Note(224.5-1),
            new Note(225.5-1),
            new Note(226.5-1),
            new Note(227.5-1),
            new Note(228.5-1),
            new Note(229.5-1),
            new Note(230.5-1),
            new Note(231.5-1),
            new Note(232.5-1),

            new Note(233.5-1),
            new Note(234.25-1),
            new Note(234.5-1),
            new Note(235.0-1),
            new Note(235.5-1),
            new Note(236.0-1),
            new Note(236.5-1),

            new Note(237.0-1),
            new Note(237.5-1),
            new Note(238.0-1),
            new Note(238.5-1),
            new Note(239.0-1),
            new Note(239.5-1),
            new Note(240.0-1),
            new Note(240.5-1),
            new Note(241.0-1),
            new Note(241.5-1),
            new Note(242.0-1),
            new Note(242.5-1),
            new Note(243.0-1),
            new Note(243.5-1),

            new Note(245.0-1),
            new Note(245.5-1),
            new Note(246.0-1),
            new Note(246.5-1),
            new Note(247.0-1),
            new Note(247.5-1),
            new Note(248.0-1),
            new Note(248.5-1),
            new Note(249.0-1),
            new Note(249.5-1),
            new Note(250.0-1),
            new Note(250.5-1),
            new Note(251.0-1),
            new Note(251.5-1),
            new Note(252.0-1),

            new Note(253.0-1),
            new Note(253.5-1),
            new Note(254.0-1),
            new Note(254.5-1),
            new Note(255.0-1),
            new Note(255.5-1),
            new Note(256.0-1),
            new Note(256.5-1),
            new Note(257.0-1),
            new Note(257.5-1),
            new Note(258.0-1),
            new Note(258.5-1),
            new Note(259.0-1),
            new Note(259.5-1),
            new Note(260.0-1),
            new Note(260.5-1),
            new Note(261.0-1),
            new Note(261.5-1),
            new Note(262.0-1),
            new Note(262.5-1),
            new Note(263.0-1),
            new Note(263.5-1),
            new Note(264.0-1),
            new Note(264.5-1),
            new Note(265.0-1),
            new Note(265.5-1),
            new Note(266.0-1),
            new Note(266.5-1),
            new Note(267.0-1),
            new Note(267.5-1),
            new Note(268.0-1),

            // PAUSE

            // SECOND part

            new Note(318.0-1),
            new Note(318.5-1),
            new Note(319.0-1),
            new Note(319.5-1),
            new Note(320.0-1),
            new Note(320.5-1),
            new Note(321.5-1),
            new Note(322.0-1),
            new Note(322.5-1),
            new Note(323.0-1),
            new Note(323.5-1),
            new Note(324.0-1),
            new Note(324.5-1),

            new Note(334.0-1),
            new Note(334.5-1),
            new Note(335.0-1),
            new Note(335.5-1),
            new Note(336.0-1),
            new Note(336.5-1),
            new Note(337.5-1),
            new Note(338.25-1),
            new Note(338.5-1),
            new Note(339.0-1),
            new Note(339.5-1),
            new Note(340.0-1),
            new Note(340.5-1),

            new Note(349.0-1),
            new Note(350.0-1),
            new Note(350.5-1),
            new Note(351.0-1),
            new Note(351.5-1),
            new Note(352.0-1),
            new Note(352.5-1),
            new Note(353.5-1),
            new Note(354.0-1),
            new Note(354.5-1),
            new Note(355.0-1),
            new Note(355.5-1),
            new Note(356.0-1),
            new Note(356.5-1),

            new Note(363.0-1),
            new Note(364.0-1),
            new Note(365.0-1),
            new Note(366.0-1),
            new Note(366.5-1),
            new Note(367.0-1),
            new Note(367.5-1),
            new Note(368.0-1),
            new Note(368.5-1),
            new Note(369.5-1),
            new Note(370.25-1),
            new Note(370.5-1),
            new Note(371.0-1),
            new Note(371.5-1),
            new Note(372.0-1),
            new Note(372.5-1),

            new Note(379.5-1),
            new Note(380.0-1),
            new Note(380.5-1),
            new Note(381.0-1),
            new Note(382.0-1),
            new Note(382.5-1),
            new Note(383.0-1),
            new Note(383.5-1),
            new Note(384.0-1),
            new Note(384.5-1),
            new Note(385.5-1),
            new Note(386.0-1),
            new Note(386.5-1),
            new Note(387.0-1),
            new Note(387.5-1),
            new Note(388.0-1),
            new Note(388.5-1),

            new Note(397.0-1),
            new Note(398.0-1),
            new Note(398.5-1),
            new Note(399.0-1),
            new Note(399.5-1),
            new Note(400.0-1),
            new Note(400.5-1),
            new Note(401.5-1),
            new Note(402.25-1),
            new Note(402.5-1),
            new Note(403.0-1),
            new Note(403.5-1),
            new Note(404.0-1),
            new Note(404.5-1),

            // OUTRO

            new Note(413.0-1),
            new Note(414.0-1),
            new Note(414.5-1),
            new Note(415.0-1),
            new Note(415.5-1),
            new Note(416.0-1),
            new Note(416.5-1),
            new Note(417.5-1),
            new Note(418.0-1),
            new Note(418.5-1),
            new Note(419.0-1),
            new Note(419.5-1),
            new Note(420.0-1),
            new Note(420.5-1),

            new Note(429.0-1),
            new Note(430.0-1),
            new Note(430.5-1),
            new Note(431.0-1),
            new Note(431.5-1),
            new Note(432.0-1),
            new Note(432.5-1),
            new Note(433.5-1),
            new Note(434.25-1),
            new Note(434.5-1),
            new Note(435.0-1),
            new Note(435.5-1),
            new Note(436.0-1),
            new Note(436.5-1),

            new Note(445.0-1),
            new Note(446.0-1),
            new Note(446.5-1),
            new Note(447.0-1),
            new Note(447.5-1),
            new Note(448.0-1),
            new Note(448.5-1),
            new Note(449.5-1),
            new Note(450.0-1),
            new Note(450.5-1),
            new Note(451.0-1),
            new Note(451.5-1),
            new Note(452.0-1),
            new Note(452.5-1),

            new Note(461.0-1),
            new Note(462.0-1),
            new Note(462.5-1),
            new Note(463.0-1),
            new Note(463.5-1),
            new Note(464.0-1),
            new Note(464.5-1),
            new Note(465.5-1),
            new Note(466.25-1),
            new Note(466.5-1),
            new Note(467.0-1),
            new Note(467.5-1),
            new Note(468.0-1),
            new Note(468.5-1),

            new Note(476.0-1),
        },

        new List<Note>()
        {
            new Note(17,   InputHandler.Input.RIGHT, Note.Position.RIGHT),
            new Note(19,   InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(21,   InputHandler.Input.RIGHT, Note.Position.RIGHT),
            new Note(23,   InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(23.5, InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),
            new Note(25,   InputHandler.Input.RIGHT, Note.Position.LEFT ),
            new Note(27,   InputHandler.Input.LEFT , Note.Position.LEFT ),
            new Note(29,   InputHandler.Input.RIGHT, Note.Position.LEFT ),
            new Note(31,   InputHandler.Input.LEFT , Note.Position.LEFT ),

            new Note(32,   InputHandler.Input.UP   , Note.Position.LEFT ),
            //new Note(32.5),
            new Note(33,   InputHandler.Input.DOWN , Note.Position.LEFT ),
            //new Note(33.5),
            //new Note(34),
            //new Note(34.5),
            new Note(35,   InputHandler.Input.LEFT , Note.Position.LEFT ),
            //new Note(35.5),
            
            new Note(36,   InputHandler.Input.UP , Note.Position.LEFT ),
            //new Note(36.5),
            new Note(37,   InputHandler.Input.DOWN , Note.Position.LEFT ),
            //new Note(37.5),
            //new Note(38),
            new Note(38.5, InputHandler.Input.RIGHT, Note.Position.LEFT ),
            new Note(39,   InputHandler.Input.DASH_RIGHT, Note.Position.LEFT ),
            //new Note(39.5),
            
            new Note(40,   InputHandler.Input.UP   , Note.Position.RIGHT),
            //new Note(40.5),
            new Note(41,   InputHandler.Input.DOWN , Note.Position.RIGHT),
            //new Note(41.5),
            //new Note(42),
            //new Note(42.5),
            new Note(43,   InputHandler.Input.RIGHT, Note.Position.RIGHT),
            //new Note(43.5),
            
            new Note(44,   InputHandler.Input.UP   , Note.Position.RIGHT),
            //new Note(44.5),
            new Note(45,   InputHandler.Input.DOWN , Note.Position.RIGHT),
            //new Note(45.5),
            new Note(46,   InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),
            new Note(46.5, InputHandler.Input.RIGHT , Note.Position.LEFT ),
            new Note(47,   InputHandler.Input.DASH_RIGHT, Note.Position.LEFT ),
            new Note(47.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            
            new Note(48,   InputHandler.Input.UP   , Note.Position.RIGHT),
            //new Note(48.5),
            new Note(49,   InputHandler.Input.DOWN , Note.Position.RIGHT),
            //new Note(49.5),
            //new Note(50),
            //new Note(50.5),
            new Note(51,   InputHandler.Input.RIGHT, Note.Position.RIGHT),
            //new Note(51.5),
            
            new Note(52,   InputHandler.Input.UP   , Note.Position.RIGHT),
            //new Note(52.5),
            new Note(53,   InputHandler.Input.DOWN , Note.Position.RIGHT),
            //new Note(53.5),
            //new Note(54),
            new Note(54.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(55,   InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),
            //new Note(55.5),
            
            new Note(56,   InputHandler.Input.UP   , Note.Position.LEFT ),
            //new Note(56.5),
            new Note(57,   InputHandler.Input.DOWN , Note.Position.LEFT ),
            //new Note(57.5),
            //new Note(58),
            //new Note(58.5),
            new Note(59,   InputHandler.Input.LEFT , Note.Position.LEFT ),
            //new Note(59.5),
            
            new Note(60,   InputHandler.Input.UP   , Note.Position.LEFT ),
            //new Note(60.5),
            new Note(61,   InputHandler.Input.DOWN , Note.Position.LEFT ),
            //new Note(61.5),
            new Note(62,   InputHandler.Input.DASH_RIGHT, Note.Position.LEFT ),
            new Note(62.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(63,   InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),

            // ----

            new Note(64,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(65,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(66,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(66.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(67,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(67.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(68,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(69,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(70.5, InputHandler.Input.UP , Note.Position.LEFT),
            new Note(71,   InputHandler.Input.DOWN , Note.Position.LEFT),

            new Note(72,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(73,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(74,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(74.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(75,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(75.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(76,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(77,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(78,   InputHandler.Input.UP , Note.Position.LEFT),
            new Note(78.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(79,   InputHandler.Input.DOWN , Note.Position.LEFT),
            new Note(79.5, InputHandler.Input.RIGHT , Note.Position.LEFT),



            new Note(80,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(81,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(82,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(82.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(83,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(83.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(84,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(85,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(86.5, InputHandler.Input.UP , Note.Position.LEFT),
            new Note(87,   InputHandler.Input.DOWN , Note.Position.LEFT),

            new Note(88,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(89,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(90,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(90.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(91,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(91.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(92,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(93,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(94,   InputHandler.Input.UP , Note.Position.LEFT),
            new Note(94.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(95,   InputHandler.Input.DOWN , Note.Position.LEFT),
            new Note(95.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            // ====

            new Note(97,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(99,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(101,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(103,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(105,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(107,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(109,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(111,   InputHandler.Input.BASS , Note.Position.MIDDLE),

            new Note(113,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(115,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(117,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(119,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(121,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(123,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(125,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(127,   InputHandler.Input.BASS , Note.Position.MIDDLE),



            new Note(32+64,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+65,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+66,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+66.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+67,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+67.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(32+68,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+69,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+70.5, InputHandler.Input.UP , Note.Position.LEFT),
            new Note(32+71,   InputHandler.Input.DOWN , Note.Position.LEFT),

            new Note(32+72,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+73,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+74,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+74.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+75,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+75.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(32+76,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+77,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+78,   InputHandler.Input.UP , Note.Position.LEFT),
            new Note(32+78.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+79,   InputHandler.Input.DOWN , Note.Position.LEFT),
            new Note(32+79.5, InputHandler.Input.RIGHT , Note.Position.LEFT),



            new Note(32+80,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+81,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+82,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+82.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+83,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+83.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(32+84,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+85,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+86.5, InputHandler.Input.UP , Note.Position.LEFT),
            new Note(32+87,   InputHandler.Input.DOWN , Note.Position.LEFT),

            new Note(32+88,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+89,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+90,   InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+90.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(32+91,   InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+91.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(32+92,   InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
            new Note(32+93,   InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(32+94,   InputHandler.Input.UP , Note.Position.LEFT),
            new Note(32+94.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(32+95,   InputHandler.Input.DOWN , Note.Position.LEFT),
            new Note(32+95.5, InputHandler.Input.RIGHT , Note.Position.LEFT),



            new Note(128,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(129,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(130,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(130.75,InputHandler.Input.DASH_RIGHT, Note.Position.LEFT),
            new Note(131,   InputHandler.Input.BASS , Note.Position.MIDDLE),

            new Note(132,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(133,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(134,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(134.75,InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),
            new Note(135,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(135.5, InputHandler.Input.DASH_RIGHT, Note.Position.LEFT),

            new Note(136,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(137,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(138,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(138.75,InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),
            new Note(139,   InputHandler.Input.BASS , Note.Position.MIDDLE),

            new Note(140,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(141,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(142,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(142.75,InputHandler.Input.DASH_RIGHT, Note.Position.LEFT),
            new Note(143,   InputHandler.Input.BASS , Note.Position.MIDDLE),
            new Note(143.5, InputHandler.Input.DASH_LEFT, Note.Position.RIGHT),



            new Note(144, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(144.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(145, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(145.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(146, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(146.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(147, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(147.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(148, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(148.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(149, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(149.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),

            new Note(150, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(150.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(151, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(151.5, InputHandler.Input.LEFT , Note.Position.RIGHT),

            new Note(152, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(152.25, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(152.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(152.75, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(153, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(153.25, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(153.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(153.75, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(154, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(154.25, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(154.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(154.75, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(155, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(155.25, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(155.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(155.75, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(156, InputHandler.Input.RIGHT , Note.Position.RIGHT),



            new Note(160, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(161, InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),

            new Note(162.25, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(162.5, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(163, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(163.5, InputHandler.Input.LEFT , Note.Position.LEFT),

            new Note(165, InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),

            new Note(165.75, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(166.25, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(166.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(166.75, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(167, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(167.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(168, InputHandler.Input.UP , Note.Position.RIGHT),

            new Note(169.75, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(170.25, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(170.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(171, InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(171.5, InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),

            new Note(174.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(175, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(175.5, InputHandler.Input.UP , Note.Position.RIGHT),

            new Note(177, InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),

            new Note(178.25, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(178.5, InputHandler.Input.RIGHT , Note.Position.LEFT),
            new Note(179, InputHandler.Input.LEFT , Note.Position.LEFT),
            new Note(179.5, InputHandler.Input.RIGHT , Note.Position.LEFT),

            new Note(181, InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),

            new Note(181.75, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(182.25, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(182.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(182.75, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(183, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(183.5, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(184, InputHandler.Input.UP , Note.Position.RIGHT),

            new Note(185.75, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(186.25, InputHandler.Input.RIGHT , Note.Position.RIGHT),
            new Note(186.5, InputHandler.Input.LEFT , Note.Position.RIGHT),
            new Note(187, InputHandler.Input.DASH_LEFT , Note.Position.RIGHT),
            new Note(187.5, InputHandler.Input.DASH_RIGHT , Note.Position.LEFT),
        },

        new List<Note>()
        {

        },
    };
}
